### ISSUE TITLE
hook получение width, hight

### ISSUE THREAD

**Issue by guzovv** [guzovv/prv-nat#1]
- [ ] необходимо имплементировать hook для которые отслеживает ширину и высоту окна viewport
- [ ] хук может принимать  html element
- [ ] если она передана хук возвращает ширину и высоту элемента
- [ ] если элемент не найден должно быть выбрашено исключение информацие  об ошибке

```ts
const [width, height] = useResize();
```

```ts
const [width, height] = useResize(htmlElement);
```

**Comment by natalka10021991** [comment]
3 часа

**Comment by guzovv** [comment]
https://github.com/guzovv/prv-nat/pull/5
